name: SmoothApp Post-Submit Tests

on: push
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1

      # Setup Java
      - name: "Setup Java" 
        uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      
      # Setup flutter 
      - name: "Setup Flutter"
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' 
      
      # Get dependencies.
      - name: "Get dependencies"
        run: ci/pub_upgrade.sh

      # Check for formatting issues
      - name: Check for formatting issues (run "flutter format . ")
        run: flutter format --set-exit-if-changed .
      
      # analyze Dart for errors
      - name: "Analyze code"
        run: flutter analyze .
      
      # Run tests
      - name: "Run Tests"
        run: ci/testing.sh
        
      - name: Flutter Pubspec Updater
        # You may pin to the exact commit or the version.
        # uses: kuanyi-ng/update-flutter-packages@ef43c3fa7e22b39df320799f82866e37e94c1b93
        uses: kuanyi-ng/update-flutter-packages@v0.1.1
        with:
          # relative path to pubspec.yaml file from root directory
          pathToPubspecFile: packages/smooth_app/pubspec.yaml # default is ./pubspec.yaml
      
      # Build apk.
      - name: "Build apk"
        run: flutter build apk --debug
        working-directory: ./packages/smooth_app
      
      # Upload generated apk to the artifacts.
      - name: "Upload APK"
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: packages/smooth_app/build/app/outputs/flutter-apk/app-debug.apk
          
          
